gText_MrHyper_Introduction::
	.string "Allow me to introduce myself - the\n"
	.string "name's MR. HYPER!\p"
	.string "Why do people call me that?\p"
	.string "Because I help POKéMON to hyper train!\p"
	.string "What is hyper training?\p"
	.string "It's a way of helping POKéMON improve\n"
	.string "the inherent stats they were born with!\p"
	.string "Why do I do this?\p"
	.string "For BOTTLE CAPs! My collection is\n"
	.string "always in need of more!\p"
	.string "Bring me a BOTTLE CAP and I'll toughen\n"
	.string "up one of your POKéMON for free!$"

gText_MrHyper_Greeting::
	.string "Do you have a BOTTLE CAP to exchange\n"
	.string "for my hyper training services?$"

gText_MrHyper_Info::
    .string "All POKéMON have unique stats known as\n"
	.string "Individual Values, or IVs for short.\p"
	.string "IVs influence a POKéMON's total stats,\n"
	.string "such as ATTACK, DEFENSE, and SPEED.\p"
	.string "One LOTAD may have high IVs in SPEED,\n"
	.string "whilst another may have low SPEED IVs.\p"
	.string "There is only one way to change a\n"
	.string "POKéMON's IVs - hyper training!\p"
	.string "Bring me a BOTTLE CAP and I'll hyper\n"
	.string "train one of your POKéMON for free!$"

gText_MrHyper_Exit::
    .string "Oh… I thought you had a BOTTLE CAP for\n"
    .string "my collection…$"

gText_MrHyper_TradeBottleCap::
	.string "A new BOTTLE CAP for my collection?\n"
	.string "Then let's get hyper training!$"

gText_MrHyper_TradeGoldCap::
	.string "Oh my goodness! Is that a GOLD CAP!?\p"
	.string "For this, I will hyper train one of your\n"
	.string "POKéMON to max out all of their IVs!$"

gText_MrHyper_TradeRustedCap::
	.string "A RUSTED CAP? I'm sorry, I can't offer\n"
	.string "my regular services for this…\p"
	.string "However, if you like, I could minimize\n"
	.string "a POKéMON's IV instead…$"
